### PR TITLE
Kubernetes 1.22.5

### PR DESCRIPTION
**Pull request by kingdonb**
I do not know if you can just merge this, or if it would break some stuff

I got the updated schemas from https://github.com/yannh/kubernetes-json-schema 👍 

I'll be testing this out, I noticed that kuby-core is still emitting a v1beta1 ingress, so I wanted to fix it, and then I saw how deep this rabbit hole goes... 😨

### CODE REVIEW

**Comment by kingdonb** [comment]
I mean, it works:

https://github.com/kingdonb/kuby_test/commit/d2557183ad96f528d644529047f0948adc6dc057#diff-36c3fbf0a82a5b3f4fab49c8b23164666113f9168231d77517ae0c3c1862b554R121

🚀 👍 

These are all generated through a script:

https://github.com/kingdonb/kuby_test/blob/main/builder.sh

It has a little Ruby widget that takes in `kuby resources` as a stream of YAML documents, filters out any secrets, and then re-outputs it to a file.

If someone wants to regenerate the manifests they can just run ./builder.rb

I made some changes to `kuby dockerfiles` as well, so that I could get them outputted to a file. I don't actually use the files in my build pipeline (it runs `kuby build -- --push` so it's always fresh, even if the dockerfiles on disk are stale)

I really like the thing you did for caching assets, and I want to do a similar thing for caching bundles. But it might be easier to just use the buildkit cache feature. IDK, I haven't tried all this yet. But I have really enjoyed working with your kube-dsl 👍

**Comment by camertron** [comment]
Hey @kingdonb, thanks for taking a look at this :)

> I do not know if you can just merge this, or if it would break some stuff

Yeah, right now Kuby supports k8s versions up to v1.19, so it's probably not a good idea to upgrade the DSL objects to v1.22 quite yet. Unfortunately kube-db is holding us back from upgrading k8s versions. That being said, I wanted to add k8s version namespacing to kube-dsl, so you'd write `KubeDSL::V1_22.namespace do` or some such. If you have any desire to work on something like that, I would very gladly review your PR :) I would also gladly merge a PR that upgrades kube-dsl to v1.19, since that's the newest supported version :)

> I got the updated schemas from https://github.com/yannh/kubernetes-json-schema

Hmm, doesn't the `generate` rake task download the schema automatically?

> These are all generated through a script

Sweet, the script looks cool! Would it be helpful to be able to access the resources programmatically instead of spawning a `kuby` command? I'm happy to help with that.

> I made some changes to `kuby dockerfiles` as well

Nice, feel like submitting a PR?

> I noticed that kuby-core is still emitting a v1beta1 ingress, so I wanted to fix it, and then I saw how deep this rabbit hole goes... 

Hahahaha yes, the k8s API is _staggeringly_ large.

> I really like the thing you did for caching assets, and I want to do a similar thing for caching bundles.

Are you referring to the thing where the assets image copies assets out of the app image? It would be really interesting to do some research around a similar approach for bundled gems (I assume that's what you meant by "bundles"). I'm quite unfamiliar with how Buildkit caching works, so I can't really speak to the sorts of speed-ups it might offer. I can however speak to the fact that `bundle install` is often the most time-consuming part of `docker build`, so speeding it up will likely result in speed-ups for anyone who uses Kuby. A few years ago I tried an approach that pre-builds and caches gems in an object storage system like S3. It's called prebundler and it's available [here](https://github.com/camertron/prebundler). Kuby's integration tests actually use prebundler and it's really helped with build times. I could see perhaps copying over all the installed gems from the previous app image and then running `bundle install` to fix up any added or removed deps.

> I have really enjoyed working with your kube-dsl 

Cool, thank you!

**Comment by kingdonb** [comment]
> changes to `kuby dockerfiles` ... feel like submitting a PR?

It's not really in shape for a PR, I just took the formatters out really, so the STDOUT could be captured and I could produce reference Dockerfiles on disk. I'm not really using them to build yet (I'm still letting `kuby build` do this job)

It's the minimum change I needed to get kuby usable for my purposes with gitops delivery, although I haven't committed to divorcing the build process from running under Ruby. I think I want to give you the maximal PR, instead, so I don't waste your time here. Don't get me wrong, I definitely want to contribute some changes back to Kuby, I just don't want to do it quite so haphazardly. I'm just getting started, I still have to use it in anger.

I have some ideas about how this could work better but I'm not sure I'm ready to share them in an RFC format quite yet.

I don't know if the generate thing was supposed to fetch the schema for me as a single file based on the version set in KUBERNETES_VERSION or what, but I think didn't work because the "usual place" for getting schemas has stopped updating, and if you follow the GitHub issues, you can find a newer place to update from. I didn't look into what was wrong with the CI process, I just cloned that forked repo that is still maintained into the vendor dir and ran `rake generate` then it worked. 👍 sledgehammer meet fly

`prebundler` sounds like something I will definitely have to use! This is a much more straightforward solution to the issue than depending on bundler caches. This is what I did: https://github.com/moby/buildkit/issues/1173#issuecomment-674649883 if you have a stable (non-ephemeral) hosted runner for your builds, I think you really can't beat this strategy, since it uses the Docker local cache, but also nothing is stopping us from using both of these strategies together?

I noticed the S3 provider doesn't quite support custom endpoints so needs to be extended in order to use with Minio! I'll be using minio since I am using the `:bare_metal` provider for Kuby, I already have a template for how to deploy Minio here on premise, and I'm already used to how it works from using it with Hephy/Deis Workflow. You have a real solid suite of tools here for using Kubernetes APIs with Ruby. I will try to keep thinking about ways to make it work better for the uses I had in mind, without contortion and try to get the tools to where I can easily use it with GitOps when you first open up the box.

I think that Minio adapter is going to be something that I can easily finish and so it can be the first (next) thing I try to contribute back here, to work with the next example that does use `prebundler`. Then maybe I can setup and establish a dev branch on my `kube-dsl` and `kuby-core` forks that upgrade everything to K8s 1.23 and exercises all the tests, and start to understand all this Sorbet stuff and what else there is I can use to test and aid in doing actual dev work on it.

I had a look at the kuby-cert-manager repo too, I don't use this to install cert-manager, but for generating ClusterIssuers it was surprising how easy it is to go across a dozen or so cert-manager releases and bring it to current release! I have to test the new version through `kuby setup` but it seems to be doable in about 3 or 4 lines changed only! What a great scaffold.

There is a lot to explore here, I honestly think I could get lost for a while, but I don't know how much time I'm going to get to work on this. Does anybody else make it a tradition in their family to work on Ruby projects over the holidays? LOL

I'd love to use this to make an actual operator/CRD controller for some purpose yet undecided. Do you think this is a thing that Kuby could be up to the task? (Or have you maybe even already tried building an operator in Kuby? There are lots of operational reasons not to do this but I wonder if it's even possible, would it be a good experience to develop such a thing?)

**Comment by camertron** [comment]
> It's not really in shape for a PR, I just took the formatters out really, so the STDOUT could be captured and I could produce reference Dockerfiles on disk. ...  I definitely want to contribute some changes back to Kuby, I just don't want to do it quite so haphazardly.

Ah ok makes sense, absolutely no rush or pressure :) I think I'm going to file an issue for this so I don't forget about it.

> I don't know if the generate thing was supposed to fetch the schema for me as a single file based on the version set in KUBERNETES_VERSION or what, but I think didn't work because the "usual place" for getting schemas has stopped updating.

Yeah, `rake generate` is supposed to fetch the version in `KUBERNETES_VERSION` and generate all the DSL files from it. I didn't realize the instrumenta repo has stopped updating, but it looks like you found the right repo to replace it. I'll update kube-dsl to point at it right away.

> `prebundler` sounds like ... a much more straightforward solution to the issue than depending on bundler caches.

Thank you, although I would hazard a guess prebundler wouldn't have been necessary if I'd had buildx and all these fancy caching strategies back when I first wrote it. Might not be necessary anymore?

> If you have a stable (non-ephemeral) hosted runner for your builds, I think you really can't beat this strategy, since it uses the Docker local cache, but also nothing is stopping us from using both of these strategies together?

Right yeah, I'm in favor of adopting better default bundle caching strategies in Kuby with buildx and perhaps publishing a prebundler plugin you can add to your Kuby config if you so desire. Could make a pretty good combo! Hopefully for a non-trivial number of `docker build`s you won't even have to run prebundler though.

> I noticed the S3 provider doesn't quite support custom endpoints so needs to be extended in order to use with Minio!

That's actually something a colleague of mine noticed a while ago. You should be able to pass in an S3 client instance instead of the various individual options, eg:

```ruby
s3 = Aws::S3::Client.new(...)

Prebundler.configure do |config|
  config.storage_backend = Prebundler::S3Backend.new(s3)
end
```

See also https://github.com/camertron/prebundler/pull/3 and https://github.com/camertron/prebundler/pull/4

> I had a look at the kuby-cert-manager repo too ... it was surprising how easy it is to go across a dozen or so cert-manager releases and bring it to current release! ... seems to be doable in about 3 or 4 lines changed only!

Nice! One thing I haven't looked into is how to upgrade the various operators Kuby uses, cert-manager being one. Does `helm upgrade` work as expected?

> Does anybody else make it a tradition in their family to work on Ruby projects over the holidays?

🙋 (although usually without my family's express approval)

> I'd love to use this to make an actual operator/CRD controller for some purpose yet undecided. Do you think this is a thing that Kuby could be up to the task?

I actually considered making Kuby an operator that would listen for instances of a `RailsApp` CRD or something, but in the end I went with a user-land tool because a) I don't have that much experience writing operators, and b) the tool can encapsulate everything end-to-end. If Kuby were an operator, people would have to install it in their cluster and then understand how to craft k8s YAML resources, etc. Obviously there's some middle ground there (could have an operator _and_ a CLI tool), but the tool approach has worked relatively well so far. It would be interesting to discuss an operator or hybrid operator/CLI approach tho.

> Have you maybe even already tried building an operator in Kuby?

Not yet, although I know it's possible in Ruby via projects like [this](https://gitlab.com/tobiaskuntzsch/kubernetes-operator). It's not written in super semantic Ruby, but it's a great place to start.

**Comment by kingdonb** [comment]
Nice, thank you so much for sharing your knowledge about this, and code, you've enabled me to go so much further so fast

> wouldn't have been necessary if I'd had buildx and all these fancy caching strategies

I added this to my caching repertoire and I think it's going to stay. I just migrated my actions from GitHub to self-hosted runners that live inside of my network (so I can keep a builder fresh in buildkit and take advantage of truly local caches)

I settled on using DigitalOcean Spaces rather than my own Minio, though the configuration is almost exactly the same.

The `prebundler` works great! It's surgically targeted precisely at the problem that I wanted to solve, namely I don't want to spend too much time compiling when it's not needed, especially if it's the same version that I already watched compile earlier. The other half of the problem is keeping the Docker cache without spending a bunch of seconds pushing and pulling it around, which is easy if you have a local runner that you can host somewhere stable that it doesn't cost you anything.

I can't think of any reason not to run this on my home network, and it dropped my par build times from about 1m45s all the way down to 30s or less. (👀 look 👀 https://github.com/kingdonb/kuby_test/actions) – For a GitOps demo, "about a minute or less from git push to production" is kind of table stakes. Now I think I can definitely use this in my GitOps demos 👍 

> https://gitlab.com/tobiaskuntzsch/kubernetes-operator

Thanks for this link! Very cool, I will check it out in more detail soon.

I see there are some strategies to use prebundler with an endpoint that don't require it to explicitly add minio support. I'll check them out and forego the PR as it's not needed. The rest of kuby, I am getting my feet wet and digging the paradigm. 

I don't really have experience writing operators either, but I think my time is coming soon! The OpenAPI basis of kube-dsl is pretty compelling. I don't fully understand it but I feel like I could pretty quickly come up to speed and wield it!

**Comment by camertron** [comment]
> I added this to my caching repertoire and I think it's going to stay.

Awesome yeah, I think I'm going to build it into Kuby if I'm ever able to carve out a little time :)

> I settled on using DigitalOcean Spaces rather than my own Minio, though the configuration is almost exactly the same.

Super cool! I know Linode's object storage offering is S3-compatible too, so you're covered pretty much wherever you go.

> `prebundler` works great! It's surgically targeted precisely at the problem that I wanted to solve.

Great, glad it's helpful!

> The other half of the problem is keeping the Docker cache without spending a bunch of seconds pushing and pulling it around, which is easy if you have a local runner that you can host somewhere stable that it doesn't cost you anything.

Yeah, how are you managing that? In my (limited) experience, GitHub actions doesn't cache Docker layers between runs, is there a way to get it to cache more effectively? You may have such a thing baked into your demo repo...

> The OpenAPI basis of kube-dsl is pretty compelling. I don't fully understand it but I feel like I could pretty quickly come up to speed and wield it!

Cool thank you, and always happy to answer questions :) I actually figured out the other day that you can ask a live k8s cluster for its entire OpenAPI spec, meaning you don't have to go looking for the static spec files in someone's repo they may not be maintaining anymore. All the code that generates Ruby from the specs lives in KubeDSL and should be reusable. The process goes something like:

1. Stand up local cluster or find OpenAPI static files somewhere.
2. Run [this tool](https://github.com/instrumenta/openapi2jsonschema) on them (doable via the [handy Docker image](https://hub.docker.com/r/garethr/openapi2jsonschema)). Converts from OpenAPI to JSON schema format.
3. Use the generator from KubeDSL to generate Ruby code.

**Comment by kingdonb** [comment]
It looks like you've got k8s 1.22 support in the mainline for some months now 👍

**Comment by kingdonb** [comment]
> > The other half of the problem is keeping the Docker cache without spending a bunch of seconds pushing and pulling it around, which is easy if you have a local runner that you can host somewhere stable that it doesn't cost you anything.
> 
> Yeah, how are you managing that? In my (limited) experience, GitHub actions doesn't cache Docker layers between runs, is there a way to get it to cache more effectively? You may have such a thing baked into your demo repo...

I used a [self-hosted runner](https://docs.github.com/en/actions/hosting-your-own-runners/about-self-hosted-runners). The way to make caching more effective is to make a "cache hit" as likely as possible and then make it as cheap as possible. So if the chance that you hit the same builder is 100% because you're hosting your a runner, and it's the only one in the rotation, sure it's a trade-off because now you own some infrastructure again.

(It also means you have to choose: do I pay to host a runner on DigitalOcean and use their S3, or do I put it on some machine in my house and host Minio here?) as sometimes the Docker cache is cleared, or a cache miss occurs for some other reason.

I tried both strategies and I did eventually settle on 100% local. Although there is nothing stopping one from putting a self-hosted runner in a cloud provider, and there are other trade-offs (like... the stakes just went up, now if my runner is badly configured and someone is able to execute their own code on it, now they're not just gaining access to some cloud nodes, they're actually inside of my house!)

**Comment by camertron** [comment]
> It looks like you've got k8s 1.22 support in the mainline for some months now 👍

Yeah, I'm trying to get the next version of Kuby out the door, so a number of the main branches in these repos are in a half-finished or finished-but-not-released state. Caring for two kids is making this very difficult 😅 

> I used a [self-hosted runner](https://docs.github.com/en/actions/hosting-your-own-runners/about-self-hosted-runners). 

Ahhh ok that makes sense!

> The way to make caching more effective is to make a "cache hit" as likely as possible and then make it as cheap as possible. So if the chance that you hit the same builder is 100% because you're hosting your a runner, and it's the only one in the rotation, sure it's a trade-off because now you own some infrastructure again.

Right yeah, if you own the hardware you can do whatever you want caching-wise. Smart.

> I tried both strategies and I did eventually settle on 100% local. Although there is nothing stopping one from putting a self-hosted runner in a cloud provider, and there are other trade-offs (like... the stakes just went up, now if my runner is badly configured and someone is able to execute their own code on it, now they're not just gaining access to some cloud nodes, they're actually inside of my house!)

Hehehe I totally understand. I always feel a little weird when GitHub asks me if I want to allow PRs from outside contributors to trigger certain actions (like deploy to prod!!) Same idea.

**Pull request closed without merging**
